/usr/local/lib/python3.8/dist-packages/gym/logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
<Section: TRAINING>
<Section: CURRICULUM>
logs/Curriculum
shelter_id 0 [0, 1, 6, 2, 5, 7, 12, 10, 9, 4, 8, 13, 3, 11, 14, 16, 15, 17, 18]
shelter_id 1 [1, 2, 7, 0, 4, 9, 8, 10, 3, 6, 5, 13, 11, 12, 14, 15, 16, 17, 18]
shelter_id 2 [2, 1, 7, 4, 8, 0, 3, 9, 10, 11, 6, 5, 13, 14, 12, 15, 17, 16, 18]
shelter_id 3 [3, 4, 8, 11, 7, 2, 14, 1, 9, 10, 15, 6, 5, 13, 0, 17, 18, 12, 16]
shelter_id 4 [4, 3, 2, 1, 8, 11, 7, 14, 0, 9, 10, 15, 6, 5, 13, 17, 18, 12, 16]
shelter_id 5 [5, 10, 9, 12, 6, 13, 7, 0, 11, 8, 1, 14, 16, 2, 3, 15, 4, 17, 18]
shelter_id 6 [6, 5, 0, 12, 10, 9, 7, 8, 13, 1, 2, 11, 3, 4, 14, 16, 15, 17, 18]
shelter_id 7 [7, 8, 9, 10, 2, 1, 11, 3, 5, 13, 6, 4, 14, 0, 12, 15, 17, 16, 18]
shelter_id 8 [8, 7, 11, 3, 9, 2, 10, 1, 4, 14, 6, 5, 13, 15, 0, 12, 17, 18, 16]
shelter_id 9 [9, 10, 5, 13, 7, 11, 8, 1, 6, 12, 2, 14, 3, 0, 15, 4, 16, 17, 18]
shelter_id 10 [10, 9, 5, 13, 7, 11, 8, 6, 1, 12, 2, 14, 3, 0, 15, 16, 4, 17, 18]
shelter_id 11 [11, 14, 8, 3, 9, 10, 7, 4, 13, 5, 15, 2, 1, 17, 6, 12, 18, 0, 16]
shelter_id 12 [12, 5, 13, 6, 10, 9, 0, 7, 16, 14, 11, 8, 1, 15, 2, 3, 17, 18, 4]
shelter_id 13 [13, 10, 9, 5, 12, 14, 7, 15, 11, 16, 6, 8, 1, 2, 17, 0, 3, 18, 4]
shelter_id 14 [14, 11, 15, 13, 17, 8, 3, 9, 10, 7, 18, 4, 5, 12, 16, 2, 1, 6, 0]
shelter_id 15 [15, 17, 14, 18, 13, 11, 16, 9, 10, 8, 7, 3, 5, 12, 4, 2, 1, 6, 0]
shelter_id 16 [16, 13, 15, 17, 18, 5, 12, 10, 14, 9, 6, 11, 7, 8, 1, 0, 3, 2, 4]
shelter_id 17 [17, 18, 15, 14, 16, 11, 13, 3, 9, 10, 8, 7, 4, 5, 12, 2, 1, 6, 0]
shelter_id 18 [18, 17, 15, 16, 14, 13, 11, 9, 3, 10, 8, 7, 5, 12, 4, 2, 1, 6, 0]
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    curriculum.run(args)
  File "/home/shimizu/project/2020/escape_navi/navi_curriculum/envs.py", line 55, in run
    sys.exit()
NameError: name 'sys' is not defined
